openapi: 3.0.0
info:
  title: Transfer Market API
  version: '1.0'
servers:
  - url: http://localhost:8081
paths:
  /transfer:
    post:
      operationId: createTransfer
      summary: Creates transfer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: Transfer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
        default:
          $ref: '#/components/schemas/ApplicationError'
  /transfer/{id}:
    get:
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
      operationId: getTransferDetails
      summary: Returns transfer details
      responses:
        '200':
          description: Transfer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferResponse'
        default:
          $ref: '#/components/schemas/ApplicationError'

components:
  schemas:
    TransferRequest:
      properties:
        playerId:
          type: integer
          format: int64
        teamIdFrom:
          type: integer
          format: int64
        teamIdTo:
          type: integer
          format: int64
    TransferResponse:
      properties:
        id:
          type: integer
          format: int64
        playerId:
          type: integer
          format: int64
        teamIdFrom:
          type: integer
          format: int64
        teamIdTo:
          type: integer
          format: int64
        transferFee:
          type: number
        transactionDate:
          type: string
          format: date
    ApplicationError:
      properties:
        message:
          type: string
      required:
        - message